config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  resources :groups
  resources :expenses, except: :new

  get '/expenses/new/:group_id', to: 'expenses#new'
  get '/users/:id/add', to: 'groups#add_users'
  post '/groups/:id/add_user(/:user_id)', to: 'groups#add_user'
  post '/expenses/:id/mark_paid/:user_id', to: 'expenses#mark_paid'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  has_many :expenses, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  # add a user to this group - update memberships
  def add_user(user)
    membership = Membership.create(user: user, group: self)
    membership.valid? ? membership : nil
  end

  # add an expense to this group - update payments
  def add_expense(expense)
    return nil unless self == expense.group
    users.each do |user|
      if user == expense.user
        Payment.create(user: user, expense: expense, paid: true)
      else
        Payment.create(user: user, expense: expense, paid: false)
      end
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:add_users, :add_user, :show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1/add_user
  # GET /groups/1/add_user.json
  def add_users
    redirect_to root_path unless current_is_member?(@group)
    @users = User.all
  end

  # POST /groups/1/add_user(/1)
  # POST /groups/1/add_user(/1).json
  def add_user
    @user = params[:user_id] ? User.find(params[:user_id]) : current_user
    @name = params[:user_id] ? @user.full_name + ' has' : 'You have'
    @group.add_user(@user)
    respond_to do |format|
      format.html { redirect_to @group, notice: "#{@name} successfully been added this group." }
      format.json { head :no_content }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @members = @group.users
    @expenses = @group.expenses if current_is_member?(@group)
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
    redirect_to root_path unless current_is_member?(@group)
    @members = @group.users
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: "#{@group.name} was successfully created." }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: "#{@group.name} was successfully updated." }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: "#{@group.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true, :class => 'p-3') do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-6 offset-lg-3">
  <div class="form-group">
    <strong><%= form.label :name, :class => 'control-label' %>:</strong>
    <%= form.text_field :name, id: :group_name, :class => 'form-control' %>
  </div>
<div class="form-group text-center">
    <%= form.submit :class => 'btn btn-primary' %>
</div>
</div>
<% end %>

app/views/groups/add_users.html.erb
<div class="text-center p-3">
  <h4 id="notice"><%= notice %></h4>
</div>

<h1 class="text-center p-3">Add A User To <%= @group.name %></h1>

<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <table class="table table-hover">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.full_name, user %></td>
            <td><%= user.email %></td>
            <% if user_is_member?(user, @group) %>
              <td class="text-center">Already A Member</td>
            <% else %>
              <td class="text-center"><%= link_to 'Add To Group', { controller: 'groups', id: @group.id, user_id: user.id, action: 'add_user'}, method: :post%></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/edit.html.erb
<h2 class="text-center">Edit Your Group</h2>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<div class="text-center p-3">
  <h4 id="notice"><%= notice %></h4>
</div>

<h1 class="text-center p-3">Join A Group</h1>

<div class="row">
  <div class="col-lg-6 offset-lg-3">
    <table class="table table-hover">
      <tbody>
        <% @groups.each do |group| %>
          <tr>
            <td><%= link_to group.name, group %></td>
            <% if current_is_member?(group) %>
              <td class="text-center">Already A Member</td>
            <% else %>
              <td class="text-center"><%= link_to 'Join Group', { controller: 'groups', id: group.id, action: 'add_user'}, method: :post%></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/groups/new.html.erb
<h2 class="text-center">Name Your New Group</h2>

<%= render 'form', group: @group, locals: { myclass: 'form-horizontal' } %>

app/views/groups/show.html.erb
<div class="text-center">
  <h4 id="notice"><%= notice %></h4>
</div>

  <div><h1 class="text-center p-3"><%= @group.name %></h1></div>
  <div class="row">
    <div class="col-lg-3">
      <h3 class="text-center">Users</h3>
      <% if @members.blank? %>
        <p class="text-center">This group has no members.</p>
      <% else %>
        <ul class="list-group">
          <% @members.each do |member| %>
            <li class="list-group-item"><%= link_to member.full_name, member %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="text-center p-3">
        <% if current_is_member?(@group) %>
          <%= link_to 'Add A User', { controller: 'groups', id: @group.id, action: 'add_users'}, :class => 'btn btn-primary m-1' %>
          <%= link_to 'Edit Group', edit_group_path, :class => 'btn btn-primary m-1' %>
          <%= link_to 'Delete Group', group_path, method: :delete, :class => 'btn btn-danger m-1' %>
        <% else %>
          <%= link_to 'Join This Group', { controller: 'groups', id: @group.id, action: 'add_user'}, method: :post, :class => 'btn btn-primary m-1' %>
        <% end %>
      </div>
    </div>

    <div class="col-lg-9">
      <h3 class="text-center">Expenses</h3>
      <% if current_is_member?(@group) %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-center">Expense</th>
              <th class="text-center">Date</th>
              <th class="text-center">Category</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
          <tbody>
            <% @expenses.each do |expense| %>
              <tr>
                <td class="text-center"><%= link_to truncate(expense.description, :length => 35, :separator => ' '), expense %></td>
                <td class="text-center"><%= expense.date.strftime("%B %d, %Y") %></td>
                <td class="text-center"><%= expense.category %></td>
                <td class="text-right"><%= number_to_currency(expense.total) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <div class="text-right">
        <%= link_to 'Add New Expense', { controller: 'expenses', group_id: @group.id, action: 'new'}, method: :get, :class => 'btn btn-primary m-1' %>
      </div>
      <% else %>
        <p class="text-center">You must join this group to see its expenses.</p>
      <% end %>
    </div>
  </div>