config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  resources :groups
  resources :expenses, except: :new

  get '/expenses/new/:group_id', to: 'expenses#new'
  get '/users/:id/add', to: 'groups#add_users'
  post '/groups/:id/add_user(/:user_id)', to: 'groups#add_user'
  post '/expenses/:id/mark_paid/:user_id', to: 'expenses#mark_paid'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    return unless logged_in?
    @groups = current_user.groups
    @expenses = current_user.expenses
  end
end

app/views/welcome/index.html.erb
<div class="text-center">
  <h4 id="notice"><%= notice %></h4>
</div>

<% if logged_in? %>
  <div><h2 class="text-center">Welcome Back, <%= current_user.first_name %>!</h2></div>
  <br>
  <div class="row">
    <div class="col-lg-3">
      <h3 class="text-center">Your Groups</h3>
      <% if @groups.blank? %>
        <p class="text-center">You haven't joined any groups yet.</p>
      <% else %>
        <ul class="list-group">
          <% @groups.each do |group| %>
            <li class="list-group-item"><%= link_to group.name, group %></li>
          <% end %>
        </ul>
      <% end %>
      <div class="text-center p-3">
        <%= link_to 'Join A Group', groups_path, :class => 'btn btn-primary m-1' %>
        <%= link_to 'Create New Group', new_group_path, :class => 'btn btn-primary m-1' %>
      </div>
    </div>

    <div class="col-lg-9">
      <h3 class="text-center">Your Expenses</h3>
      <% if @expenses.blank? %>
        <p class="text-center">You currently have no expenses.</p>
      <% else %>
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-center">Expense</th>
              <th class="text-center">Group</th>
              <th class="text-center">Date</th>
              <th class="text-center">Category</th>
              <th class="text-center">Total</th>
            </tr>
          </thead>
          <tbody>
            <% @expenses.each do |expense| %>
              <tr>
                <td class="text-center"><%= link_to truncate(expense.description, :length => 25, :separator => ' '), expense %></td>
                <% @group = group(expense.group_id) %>
                <td class="text-center"><%= link_to @group.name, @group%></td>
                <td class="text-center"><%= expense.date.strftime("%B %d, %Y") %></td>
                <td class="text-center"><%= expense.category %></td>
                <td class="text-right"><%= number_to_currency(expense.total) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-lg-12">
      <h1 class="text-center">Welcome to PayBack</h1>
      <p class="text-center"><%= link_to 'Sign up', new_user_path%> or <%= link_to 'log in', '/login' %> to get started!</p>
    </div>
  </div>
<% end %>