config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, except: :index
  resources :groups
  resources :expenses, except: :new

  get '/expenses/new/:group_id', to: 'expenses#new'
  get '/users/:id/add', to: 'groups#add_users'
  post '/groups/:id/add_user(/:user_id)', to: 'groups#add_user'
  post '/expenses/:id/mark_paid/:user_id', to: 'expenses#mark_paid'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:mark_paid, :show, :edit, :update, :destroy]

  # GET /expenses/new
  def new
    return unless params[:group_id]
    @group = Group.find(params[:group_id])
    redirect_to root_path unless current_is_member?(@group)
    @users = @group.users
    set_categories
    @expense = Expense.new(group_id: @group.id)
  end

  # GET /expenses/1/edit
  def edit
    return unless params[:group_id]
    @group = Group.find(params[:group_id])
    redirect_to root_path unless current_is_member?(@group)
    @users = @group.users
    set_categories
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)
    create_redirect(@expense)
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /expenses/1/mark_paid/1
  # POST /expenses/1/mark_paid/1.json
  def mark_paid
    @payment = Payment.where(
      user_id: params[:user_id],
      expense_id: params[:id]
    ).first
    @payment.update(paid: !@payment.paid)
    redirect_back fallback_location: @expense
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
    @group = Group.find(@expense.group_id)
    redirect_to root_path unless current_is_member?(@group)
    @who_paid = User.find(@expense.user_id)
    @payers = @expense.users.select('users.*, payments.paid as paid')
    @per_person = @expense.total.to_f / @payers.length
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def expense_params
    params.require(:expense).permit(
      :date,
      :total,
      :description,
      :user_id,
      :group_id,
      :category
    )
  end

  def set_categories
    @categories = [
      ['Food & Drink', 'Food & Drink'],
      ['Home', 'Home'],
      ['Transportation', 'Transportation'],
      ['Utilities', 'Utilities'],
      ['Entertainment', 'Entertainment'],
      ['Other', 'Other']
    ]
  end

  def create_payments(expense)
    @group = Group.find(expense.group_id)
    @group.users.each do |user|
      @paid = user.id == expense.user_id
      @payment = Payment.new(expense: expense, user: user, paid: @paid)
      @payment.save
    end
  end

  def create_redirect(expense)
    respond_to do |format|
      if expense.save
        create_payments(expense)
        format.html { redirect_to expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: expense }
      else
        format.html { render controller: 'expenses', action: 'new', group_id: expense_params[:group_id] }
        format.json { render json: expense.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true, :class => 'form p-3') do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="col-lg-6 offset-lg-3">

  <div class="form-group">
    <strong><%= form.label :description %>:</strong>
    <%= form.text_field :description, id: :expense_description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <strong><%= form.label :total %>:</strong>
    <%= form.number_field :total, min: 0, step: 0.01, placeholder: 0.00, class: 'form-control' %>
  </div>

    <div class="form-group">
    <strong><%= form.label :date %>:</strong>
    <br>
    <%= form.date_select :date, {:order => [:month, :day, :year]} %>
  </div>

  <div class="form-group">
    <strong><%= form.label :user_id, 'Who Paid:' %></strong>
    <%= form.collection_select :user_id, @users, :id, :full_name, {prompt: false}, {class: "form-control"}%>
  </div>

  <div class="form-group">
    <strong><%= form.label :category %>:</strong>
    <%= form.select :category, options_for_select(@categories), {prompt: false}, {class: "form-control"}%>
  </div>

  <div class="form-group text-center">
    <%= form.hidden_field :group_id %>
    <%= form.submit :class => 'btn btn-success'%>
  </div>
</div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<div class="text-center p-3">
  <h4 id="notice"><%= notice %></h4>
</div>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Total</th>
      <th>Description</th>
      <th>User</th>
      <th>Group</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.date %></td>
        <td><%= expense.total %></td>
        <td><%= expense.description %></td>
        <td><%= expense.user %></td>
        <td><%= expense.group %></td>
        <td><%= expense.category %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h3 class="text-center">Enter New Expense Details</h3>

<%= render 'form', expense: @expense %>

app/views/expenses/show.html.erb
<div class="text-center">
  <h4 id="notice"><%= notice %></h4>
</div>

<div><h1 class="text-center p-3"><%= @expense.description %>: <%= number_to_currency(@expense.total) %></h1></div>
<div class="row">
  <div class="col-lg-4 offset-lg-4 text-center">
    <h3>
      Date: <%= @expense.date.strftime("%B %d, %Y") %>
    </h3>
  </div>
</div>
<div class="row">
  <div class="col-lg-3">
    <h3 class="text-center">Details</h3>
    <ul class="list-group">
      <li class="list-group-item"><strong>Who Paid: </strong><%= link_to @who_paid.full_name, @who_paid %></li>
      <li class="list-group-item"><strong>Group: </strong><%= link_to @group.name, @group %></li>
      <li class="list-group-item"><strong>Category: </strong><%= @expense.category %></li>
    </ul>
    <div class="text-center p-3">
      <%= link_to 'Add New Expense', { controller: 'expenses', group_id: @group.id, action: 'new'}, method: :get, :class => 'btn btn-primary m-1' %>
      <%= link_to 'Delete Expense', expense_path, method: :delete, :class => 'btn btn-danger m-1' %>
    </div>
</div>

<div class="col-lg-8 offset-lg-1">
               <h3 class="text-center">Users</h3>
      <% if @payers.blank? %>
          <p class="text-center">There are no users for this expense.</p>
      <% else %>

     <table class="table table-hover">
        <thead>
          <tr>
            <th class="text-center">User</th>
            <th class="text-center">Status</th>
            <th class="text-center">Amount</th>
            <th class="text-center">Update</th>
          </tr>
        </thead>
        <tbody>
          <% @payers.each do |user| %>
          <tr>
            <td class="text-center vert-aligned"><%= link_to user.full_name, user %></td>
            <% if user.paid %>
              <td class="text-center text-paid vert-aligned">Paid</td>
              <td class="text-right text-paid vert-aligned"><%= number_to_currency(@per_person) %></td>
              <% unless user.id == @expense.user_id %>
                <td class="text-center"><%= link_to 'Mark Unpaid', { controller: 'expenses', id: @expense.id, user_id: user.id, action: 'mark_paid'}, method: :post, :class => 'btn btn-unpaid' %></td>
              <% end %>
            <% else %>
              <td class="text-center text-unpaid vert-aligned">Unpaid</td>
              <td class="text-right text-unpaid vert-aligned"><%= number_to_currency(@per_person) %></td>
              <td class="text-center"><%= link_to 'Mark Paid', { controller: 'expenses', id: @expense.id, user_id: user.id, action: 'mark_paid'}, method: :post, :class => 'btn btn-paid' %></td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>

    </div>
  </div>